#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🤔🤔🤔🤔 Trying to build your project before push. 🤔🤔🤔🤔'

npm run build ||
(
    echo '❌👷🔨❌ Better call Hessar... Because your build failed ❌👷🔨❌
            React build failed: View the errors above to see why.
    '
    false;
)